---
name: deploy_prereleased

on:
  release:
    types:
      - prereleased

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: test
        run: |
          echo "date=$(date +%Y%m%d-%H%M%S)"
          echo "git info ${GITHUB_EVENT_NAME}_${GITHUB_REF_NAME}"
          echo $GITHUB_EVENT_NAME
