name: Release

on:
  push:
    tags:
      - 'v*.*.*'


permissions:
  actions: 'write'
  packages: 'write'
  contents: 'write'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo 'testbytest release' > build.txt

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          make_latest: true
          files: build.txt
