name: Release

on:
  push:
    tags:
      - 'v*.*.*'


permissions:
  actions: 'write'
  packages: 'write'
  contents: 'write'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo 'testbytest release' > build.txt

      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          make_latest: true
          files: build.txt

      - name: Get release body
        id: release_info
        uses: actions/github-script@v7
        with:
          script: |
            const release_id = Number(`${{ steps.release.outputs.id }}`);
            const { data } = await github.rest.repos.getRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id
            });
            core.setOutput('body', data.body || '');
            core.setOutput('html_url', data.html_url);
            core.setOutput('tag_name', data.tag_name);

      - name: Debug
        run: |
          echo "release body: ${{ steps.release_info.outputs.body }}"
          echo "tag_name : ${{ steps.release_info.outputs.tag_name }}"
